import React from "react";

interface FormattedAnalysisProps {
  analysis: string;
}

export function FormattedAnalysis({ analysis }: FormattedAnalysisProps) {
  // Debug log
  console.log("FormattedAnalysis received:", analysis);

  // Parse the analysis text and format it
  const formatAnalysis = (text: string) => {
    const lines = text.split("\n");
    const elements: React.ReactNode[] = [];

    console.log("Processing", lines.length, "lines");
    console.log("Raw text:", text);

    lines.forEach((line, index) => {
      const trimmedLine = line.trim();

      console.log(`Line ${index}: "${trimmedLine}"`);

      // Skip empty lines
      if (!trimmedLine) {
        return;
      }

      // Lines with bold labels (e.g., "* **Bones:** description" or "**Bones:** description")
      // Format is: * **Label:** description (colon is inside the **)
      const boldMatch = trimmedLine.match(/^\* \*\*([^*]+?):\*\*\s*(.*)/) ||
                        trimmedLine.match(/^\*\*([^*]+?):\*\*\s*(.*)/);

      if (boldMatch) {
        const [, label, description] = boldMatch;
        console.log(`  -> Matched bold label: "${label}" with desc: "${description}"`);

        // Special handling for disclaimer - skip it
        if (label.toLowerCase().includes("disclaimer")) {
          return;
        }

        elements.push(
          <div key={index} className="mb-4 mt-2 p-3 bg-slate-50 rounded-lg border-l-4 border-teal-500">
            <span className="font-bold text-teal-700 text-base">
              {label}:
            </span>
            <span className="text-slate-700 ml-2 leading-relaxed">
              {description.trim()}
            </span>
          </div>
        );
        return;
      }

      // Header line with ** (like "**Key features:**" or "**Key features**")
      if (trimmedLine.startsWith("**") && trimmedLine.endsWith("**")) {
        const headerText = trimmedLine.replace(/\*\*/g, "").replace(/:$/, "");
        console.log(`  -> Matched header: "${headerText}"`);
        elements.push(
          <h3 key={index} className="text-xl font-bold text-teal-600 mt-6 mb-4">
            {headerText}
          </h3>
        );
        return;
      }

      console.log(`  -> Regular paragraph`);
      // Regular text paragraphs
      elements.push(
        <p key={index} className="text-slate-700 mb-3 leading-relaxed">
          {trimmedLine}
        </p>
      );
    });

    return elements;
  };

  return (
    <div className="space-y-4">
      {formatAnalysis(analysis)}

      {/* Always show disclaimer at the end */}
      <div className="mt-6 p-4 bg-amber-50 border-l-4 border-amber-500 rounded-r-lg">
        <div className="flex items-start gap-3">
          <div className="text-2xl">⚠️</div>
          <div>
            <p className="text-sm font-bold text-amber-900 mb-1">
              Important Medical Disclaimer
            </p>
            <p className="text-xs text-amber-800 leading-relaxed">
              This analysis is generated by AI for informational purposes only.
              It does not constitute medical advice, diagnosis, or treatment.
              Always consult with a qualified healthcare professional for
              medical decisions and interpretation of medical images.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
